# Generated by Django 3.2.4 on 2021-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name_plural': 'Merch'},
        ),
        migrations.AddField(
            model_name='merch',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
