# Generated by Django 3.2.4 on 2021-06-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_test_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
