# Generated by Django 3.2.4 on 2021-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
