# Generated by Django 3.2.4 on 2021-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_position_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='symbol',
            field=models.CharField(default='sbl', max_length=10),
        ),
    ]
