# Generated by Django 3.2.4 on 2021-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_position_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
