# Generated by Django 3.2.4 on 2021-06-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='crypto', max_length=100, primary_key=True, serialize=False),
        ),
    ]
