# Generated by Django 3.2.4 on 2021-08-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
