# Generated by Django 3.2.4 on 2021-08-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('home', '0012_delete_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('token_symbol', models.CharField(max_length=10)),
                ('token_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gbp_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('token_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_bought', to='profiles.userprofile')),
            ],
        ),
    ]
