# Generated by Django 3.2.4 on 2021-08-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('home', '0013_buytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytoken',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_bought', to='profiles.userprofile'),
        ),
    ]
