# Generated by Django 3.2.4 on 2021-08-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_buytoken_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytoken',
            name='current_total',
        ),
    ]
