# Generated by Django 3.2.4 on 2021-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_buytoken_current_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytoken',
            name='token_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
