# Generated by Django 3.2.4 on 2021-08-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210803_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytoken',
            name='gbp_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='buytoken',
            name='token_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
