# Generated by Django 3.2.4 on 2021-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_buytoken_token_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytoken',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='buytoken',
            name='token_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=30),
        ),
    ]
