# Generated by Django 3.2.4 on 2021-08-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('home', '0023_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_allowance', to='profiles.userprofile'),
        ),
    ]
