# Generated by Django 3.2.4 on 2021-08-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_allowance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytoken',
            name='token_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
