# Generated by Django 3.2.4 on 2021-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210811_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='crypto', max_length=100, primary_key=True, serialize=False),
        ),
    ]
