# Generated by Django 3.2.4 on 2021-08-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210811_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
