# Generated by Django 3.2.4 on 2021-08-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tokenid', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(max_length=10)),
                ('image', models.URLField()),
                ('price', models.FloatField(blank=True, default=0)),
                ('rank', models.CharField(max_length=10)),
                ('market_cap', models.CharField(max_length=200)),
                ('price_change', models.CharField(max_length=200)),
            ],
        ),
    ]
