# Generated by Django 3.2.4 on 2021-08-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='tokenid',
            new_name='tokeni',
        ),
    ]
