# Generated by Django 3.2.4 on 2021-08-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_tokenid_position_tokeni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='tokeni',
            new_name='tokenid',
        ),
    ]
