# Generated by Django 3.2.4 on 2021-08-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_tokeni_position_tokenid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
