# Generated by Django 3.2.4 on 2021-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='tokenid',
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
